// FE/src/components/searchBar/GuestPopup.jsx
import React, { useState, useEffect, useRef } from "react";
import "./Guest.css";

const GuestPopup = ({ totalGuests, onClose }) => {
  const [adults, setAdults] = useState(2);
  const [children, setChildren] = useState(0);
  const [infants, setInfants] = useState(0);
  const modalRef = useRef(null);

  useEffect(() => {
    const handleClickOutside = (event) => {
      if (modalRef.current && !modalRef.current.contains(event.target)) {
        onClose(adults + children + infants);
      }
    };

    document.addEventListener("mousedown", handleClickOutside);
    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
    };
  }, [onClose, adults, children, infants]);

  const increment = (type) => {
    if (type === "adults") setAdults(adults + 1);
    if (type === "children") setChildren(children + 1);
    if (type === "infants") setInfants(infants + 1);
  };

  const decrement = (type) => {
    if (type === "adults" && adults > 0) setAdults(adults - 1);
    if (type === "children" && children > 0) setChildren(children - 1);
    if (type === "infants" && infants > 0) setInfants(infants - 1);
  };

  const handleApply = () => {
    onClose(adults + children + infants);
  };

  return (
    <div className="fixed inset-0 bg-gray-500 bg-opacity-75 flex justify-center items-center text-black">
      <div
        ref={modalRef}
        className="guest-popup bg-white p-6 rounded-lg shadow-lg w-80"
      >
        <div className="space-y-6">
          <div className="flex justify-between items-center">
            <div>
              <div className="font-bold text-gray-800">성인</div>
              <div className="text-gray-500 text-sm">만 13세 이상</div>
            </div>
            <div className="flex items-center space-x-2">
              <button
                className="text-gray-600 bg-gray-300 hover:bg-gray-400 rounded-full w-8 h-8 flex items-center justify-center"
                onClick={() => decrement("adults")}
              >
                -
              </button>
              <div>{adults}</div>
              <button
                className="text-gray-600 bg-gray-300 hover:bg-gray-400 rounded-full w-8 h-8 flex items-center justify-center"
                onClick={() => increment("adults")}
              >
                +
              </button>
            </div>
          </div>
          <div className="flex justify-between items-center">
            <div>
              <div className="font-bold text-gray-800">어린이</div>
              <div className="text-gray-500 text-sm">2~12세</div>
            </div>
            <div className="flex items-center space-x-2">
              <button
                className="text-gray-600 bg-gray-300 hover:bg-gray-400 rounded-full w-8 h-8 flex items-center justify-center"
                onClick={() => decrement("children")}
              >
                -
              </button>
              <div>{children}</div>
              <button
                className="text-gray-600 bg-gray-300 hover:bg-gray-400 rounded-full w-8 h-8 flex items-center justify-center"
                onClick={() => increment("children")}
              >
                +
              </button>
            </div>
          </div>
          <div className="flex justify-between items-center">
            <div>
              <div className="font-bold text-gray-800">유아</div>
              <div className="text-gray-500 text-sm">2세 미만</div>
            </div>
            <div className="flex items-center space-x-2">
              <button
                className="text-gray-600 bg-gray-300 hover:bg-gray-400 rounded-full w-8 h-8 flex items-center justify-center"
                onClick={() => decrement("infants")}
              >
                -
              </button>
              <div>{infants}</div>
              <button
                className="text-gray-600 bg-gray-300 hover:bg-gray-400 rounded-full w-8 h-8 flex items-center justify-center"
                onClick={() => increment("infants")}
              >
                +
              </button>
            </div>
          </div>
        </div>
        <button className="apply-button mt-6" onClick={handleApply}>
          적용
        </button>
      </div>
    </div>
  );
};

export default GuestPopup;

// fe/src/components/GuestPopup.svelte
<script>
  import { onMount, onDestroy } from 'svelte';

  export let total = 0;
  export let onClose;

  let adults = 2;
  let children = 0;
  let infants = 0;

  const updateTotal = () => {
    total = adults + children + infants;
  };

  const increment = (type) => {
    if (type === 'adults') adults++;
    if (type === 'children') children++;
    if (type === 'infants') infants++;
    updateTotal();
  };

  const decrement = (type) => {
    if (type === 'adults' && adults > 1) adults--; // Ensure adults do not go below 1
    if (type === 'children' && children > 0) children--;
    if (type === 'infants' && infants > 0) infants--;
    updateTotal();
  };

  const handleClickOutside = (event) => {
    if (!event.target.closest('.popup')) {
      updateTotal();
      onClose(total);
    }
  };

  onMount(() => {
    document.addEventListener('mousedown', handleClickOutside);
  });

  onDestroy(() => {
    document.removeEventListener('mousedown', handleClickOutside);
  });
</script>

<div class="fixed inset-0 bg-gray-500 bg-opacity-75 flex justify-center items-center text-black">
  <div class="popup bg-white p-6 rounded-lg shadow-lg w-80">
    <div class="space-y-6">
      <div class="flex justify-between items-center">
        <div>
          <div class="font-bold text-gray-800">성인</div>
          <div class="text-gray-500 text-sm">만 13세 이상</div>
        </div>
        <div class="flex items-center space-x-2">
          <button class="text-gray-600 bg-gray-300 hover:bg-gray-400 rounded-full w-8 h-8 flex items-center justify-center" on:click={() => decrement('adults')}>-</button>
          <div>{adults}</div>
          <button class="text-gray-600 bg-gray-300 hover:bg-gray-400 rounded-full w-8 h-8 flex items-center justify-center" on:click={() => increment('adults')}>+</button>
        </div>
      </div>

      <div class="flex justify-between items-center">
        <div>
          <div class="font-bold text-gray-800">어린이</div>
          <div class="text-gray-500 text-sm">만 2-12세</div>
        </div>
        <div class="flex items-center space-x-2">
          <button class="text-gray-600 bg-gray-300 hover:bg-gray-400 rounded-full w-8 h-8 flex items-center justify-center" on:click={() => decrement('children')}>-</button>
          <div>{children}</div>
          <button class="text-gray-600 bg-gray-300 hover:bg-gray-400 rounded-full w-8 h-8 flex items-center justify-center" on:click={() => increment('children')}>+</button>
        </div>
      </div>

      <div class="flex justify-between items-center">
        <div>
          <div class="font-bold text-gray-800">유아</div>
          <div class="text-gray-500 text-sm">만 2세 미만</div>
        </div>
        <div class="flex items-center space-x-2">
          <button class="text-gray-600 bg-gray-300 hover:bg-gray-400 rounded-full w-8 h-8 flex items-center justify-center" on:click={() => decrement('infants')}>-</button>
          <div>{infants}</div>
          <button class="text-gray-600 bg-gray-300 hover:bg-gray-400 rounded-full w-8 h-8 flex items-center justify-center" on:click={() => increment('infants')}>+</button>
        </div>
      </div>
    </div>
    
  </div>
</div>

<style>
  .popup {
    z-index: 50; /* Ensure the popup is above other elements */
  }
  button {
    cursor: pointer;
  }
</style>
