// FE/src/components/searchBar/SearchBar.jsx
import React, { useState } from "react";
import { format, differenceInDays } from "date-fns";
import DatePopup from "./DatePopup";
import RatePopup from "./RatePopup";
import GuestPopup from "./GuestPopup";
import "./searchbar.css";

const SearchBar = () => {
  const [checkIn, setCheckIn] = useState(null);
  const [checkOut, setCheckOut] = useState(null);
  const [selectedMinPrice, setSelectedMinPrice] = useState(100000);
  const [selectedMaxPrice, setSelectedMaxPrice] = useState(1000000);
  const [totalGuests, setTotalGuests] = useState(0);
  const [onDatePickerPopup, setOnDatePickerPopup] = useState(false);
  const [onRatePopup, setOnRatePopup] = useState(false);
  const [onGuestPopup, setOnGuestPopup] = useState(false);

  const dateFormat = "M월 d일";
  const urlDateFormat = "yyyy-MM-dd";
  const dowLabels = ["일", "월", "화", "수", "목", "금", "토"];
  const monthLabels = [
    "1월",
    "2월",
    "3월",
    "4월",
    "5월",
    "6월",
    "7월",
    "8월",
    "9월",
    "10월",
    "11월",
    "12월",
  ];

  const toggleDatePicker = () => setOnDatePickerPopup(!onDatePickerPopup);
  const toggleRatePopup = () => setOnRatePopup(!onRatePopup);
  const toggleGuestPopup = () => setOnGuestPopup(!onGuestPopup);

  const formatDate = (dateString) =>
    (dateString && format(new Date(dateString), dateFormat)) || "";
  const formatUrlDate = (dateString) =>
    (dateString && format(new Date(dateString), "yyyy-MM-dd")) || "";

  const urlFormmattedCheckIn = formatUrlDate(checkIn);
  const urlFormmattedCheckOut = formatUrlDate(checkOut);
  const formattedCheckIn = formatDate(checkIn);
  const formattedCheckOut = formatDate(checkOut);

  const handleDateSelected = ({ startDate, endDate }) => {
    // setOnDatePickerPopup(!onDatePickerPopup);
    setCheckIn(startDate);
    setCheckOut(endDate);
  };

  const handleRateSelected = (min, max) => {
    setOnRatePopup(!onRatePopup);
    setSelectedMinPrice(min);
    setSelectedMaxPrice(max);
  };

  const handleGuestsSelected = (total) => {
    setOnGuestPopup(!onGuestPopup);
    setTotalGuests(total);
  };

  const handleSearch = () => {
    const checkInDate = urlFormmattedCheckIn;
    const checkOutDate = urlFormmattedCheckOut;
    const length = differenceInDays(new Date(checkOut), new Date(checkIn));
    const url = `/homes?checkin=${checkInDate}&checkout=${checkOutDate}&length=${length}&capacity=${totalGuests}&price_min=${selectedMinPrice}&price_max=${selectedMaxPrice}`;
    window.location.href = url;
  };

  return (
    <div className="search-bar-container">
      <div className="search-bar">
        <button
          type="button"
          className="search-bar-button"
          onClick={toggleDatePicker}
        >
          <div className="label">체크인</div>
          <div className="value">{formattedCheckIn || "날짜 입력"}</div>
        </button>
        <button
          type="button"
          className="search-bar-button"
          onClick={toggleDatePicker}
        >
          <div className="label">체크아웃</div>
          <div className="value">{formattedCheckOut || "날짜 입력"}</div>
        </button>
        <button
          type="button"
          className="search-bar-button"
          onClick={toggleRatePopup}
        >
          <div className="label">요금</div>
          <div className="value">
            ₩{selectedMinPrice.toLocaleString()} - ₩
            {selectedMaxPrice.toLocaleString()}
          </div>
        </button>
        <button
          type="button"
          className="search-bar-button"
          onClick={toggleGuestPopup}
        >
          <div className="label">인원</div>
          <div className="value">게스트 {totalGuests}명</div>
        </button>
        <div className="search-icon-container">
          <button className="search-icon-button" onClick={handleSearch}>
            <svg
              className="search-icon"
              fill="currentColor"
              viewBox="0 0 20 20"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                fillRule="evenodd"
                d="M12.9 14.32a8 8 0 111.414-1.414l4.294 4.294-1.414 1.414-4.294-4.294zM8 14a6 6 0 100-12 6 6 0 000 12z"
                clipRule="evenodd"
              ></path>
            </svg>
          </button>
        </div>

        {onDatePickerPopup && (
          <DatePopup
            checkIn={checkIn}
            checkOut={checkOut}
            dowLabels={dowLabels}
            monthLabels={monthLabels}
            onDateSelected={handleDateSelected}
            onToggle={toggleDatePicker}
          />
        )}
      </div>

      {onRatePopup && (
        <RatePopup
          selectedMinPrice={selectedMinPrice}
          selectedMaxPrice={selectedMaxPrice}
          onClose={handleRateSelected}
        />
      )}

      {onGuestPopup && (
        <GuestPopup totalGuests={totalGuests} onClose={handleGuestsSelected} />
      )}
    </div>
  );
};

export default SearchBar;

// src/components/SearchBar.svelte
<script>
  import { format, differenceInDays } from 'date-fns';
  import DatePickerComponent from './DatePickerComponent.svelte';
  import RatePopup from './RatePopup.svelte';
  import GuestPopup from './GuestPopup.svelte';

  export let checkIn;
  export let checkOut;
  export let selectedMinPrice = 100000;
  export let selectedMaxPrice = 1000000;
  export let totalGuests = 0;

  let dateFormat = 'M월 d일';
  let urlDateFormat = 'yyyy-MM-dd';
  let onDatePickerPopup = false;
  let onRatePopup = false;
  let onGuestPopup = false;
  const dowLabels = ["일", "월", "화", "수", "목", "금", "토"];
  const monthLabels = ["1월", "2월", "3월", "4월", "5월", "6월", "7월", "8월", "9월", "10월", "11월", "12월"];

  const toggleDatePicker = () => {
    onDatePickerPopup = !onDatePickerPopup;
  };

  const toggleRatePopup = () => {
    onRatePopup = !onRatePopup;
  };

  const toggleGuestPopup = () => {
    onGuestPopup = !onGuestPopup;
  };

  const formatDate = (dateString) => (dateString && format(new Date(dateString), dateFormat)) || '';
  const formatUrlDate = (dateString) => (dateString && format(new Date(dateString), 'yyyy-MM-dd')) || '';


  $: urlFormmattedCheckIn = formatUrlDate(checkIn);
  $: urlFormmattedCheckOut = formatUrlDate(checkOut);
  $: formattedCheckIn = formatDate(checkIn);
  $: formattedCheckOut = formatDate(checkOut);
  

  const handleDateSelected = (e) => {
    const { startDate, endDate } = e.detail;
    checkIn = startDate;
    checkOut = endDate;
    toggleDatePicker();
  };

  const handleRateSelected = (min, max) => {
    selectedMinPrice = min;
    selectedMaxPrice = max;
    toggleRatePopup();
  };

  const handleGuestsSelected = (total) => {
    totalGuests = total;
    toggleGuestPopup();
  }; 

  const handleSearch = () => {
    const checkInDate = urlFormmattedCheckIn;
    const checkOutDate = urlFormmattedCheckOut;
    const length = differenceInDays(new Date(checkOut), new Date(checkIn));
    const url = `/homes?checkin=${checkInDate}&checkout=${checkOutDate}&length=${length}&capacity=${totalGuests}&price_min=${selectedMinPrice}&price_max=${selectedMaxPrice}`;
    window.location.href = url;
  };
</script>

<div class="fixed top-24 left-1/2 transform -translate-x-1/2 w-full max-w-4xl">
  <div class="bg-white shadow-md rounded-full flex items-center w-full">
    <button type="button" class="flex-grow px-6 py-4 border-r text-left" on:click={toggleDatePicker}>
      <div class="text-xs font-semibold text-gray-600">체크인</div>
      <div class="text-sm text-gray-800">{formattedCheckIn || '날짜 입력'}</div>
    </button>
    <button type="button" class="flex-grow px-6 py-4 border-r text-left" on:click={toggleDatePicker}>
      <div class="text-xs font-semibold text-gray-600">체크아웃</div>
      <div class="text-sm text-gray-800">{formattedCheckOut || '날짜 입력'}</div>
    </button>
    <button type="button" class="flex-grow px-6 py-4 border-r text-left" on:click={toggleRatePopup}>
      <div class="text-xs font-semibold text-gray-600">요금</div>
      <div class="text-sm text-gray-800">₩{selectedMinPrice.toLocaleString()} - ₩{selectedMaxPrice.toLocaleString()}</div>
    </button>
    <button type="button" class="flex-grow px-6 py-4 border-r text-left" on:click={toggleGuestPopup}>
      <div class="text-xs font-semibold text-gray-600">인원</div>
      <div class="text-sm text-gray-800">게스트 {totalGuests}명</div>
    </button>
    <div class="px-4 py-4">
      <button class="bg-red-500 text-white rounded-full p-2 focus:outline-none" on:click={handleSearch}>
        <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M12.9 14.32a8 8 0 111.414-1.414l4.294 4.294-1.414 1.414-4.294-4.294zM8 14a6 6 0 100-12 6 6 0 000 12z" clip-rule="evenodd"></path>
        </svg>
      </button>
    </div>
  </div>
</div>

{#if onDatePickerPopup}
  <DatePickerComponent
    bind:checkIn
    bind:checkOut
    {dowLabels}
    {monthLabels}
    {onDatePickerPopup}
    on:dateSelected={handleDateSelected}
    on:toggle={toggleDatePicker}
  />
{/if}

{#if onRatePopup}
  <RatePopup bind:selectedMinPrice={selectedMinPrice} bind:selectedMaxPrice={selectedMaxPrice} onClose={handleRateSelected} />
{/if}

{#if onGuestPopup}
  <GuestPopup bind:total={totalGuests} onClose={handleGuestsSelected} />
{/if}

<style>
  .border-r {
    border-right: 1px solid #e5e7eb; /* Tailwind's gray-200 color */
  }
</style>
